<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Add_Manager.aspx.cs" Inherits="WebApplication4.Add_Manager" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br /><br /><br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SSConnectionString %>" 
        SelectCommand="SELECT * FROM [Admintable]"
        InsertCommand="INSERT INTO Admintable VALUES (@name, @km_h, @image)"
         UpdateCommand="UPDATE Admintable SET name = @name, km_h= @km_h, image = @image WHERE Id = @Id"
         DeleteCommand="DELETE FROM Admintable WHERE Id = @Id">
    <InsertParameters>
        <asp:ControlParameter Name="name" ControlID="txtprice" Type="String" />
        <asp:ControlParameter Name="image" ControlID="txtimage" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="name" Type="String" />
        <asp:Parameter Name="km_h" Type="Int32" />
        <asp:Parameter Name="image" Type="String" />
        <asp:Parameter Name="Tid" Type="Int32" />
    </UpdateParameters>
    <DeleteParameters>
        <asp:Parameter Name="Tid" Type="Int32" />
    </DeleteParameters>
        </asp:SqlDataSource>

    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" 
        DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" 
        GridLines="None" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="Username" HeaderText="Username" 
                SortExpression="Username" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Password" HeaderText="Password" 
                SortExpression="Password" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
     <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
    <tr>
        <td style="width: 150px">
            Username:&nbsp;&nbsp; <br />
            <asp:TextBox ID="txtdes" runat="server" Width="140" />
        </td>
        <td style="width: 150px">
            Name:<br />
            <asp:TextBox ID="txtprice" runat="server" Width="140" />
        </td>
        <td style="width: 150px">
            Password:<br />
            <asp:TextBox ID="txtitems" runat="server" Width="140px" />
        </td>
        <td style="width: 100px">
            <asp:Button ID="btnAdd" runat="server" Text="Add Item" OnClick="Insert" 
                Width="70px" />
        </td>
    </tr>
</table>
</asp:Content>
