<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Admin_Event.aspx.cs" Inherits="WebApplication4.Admin_Event" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br /><br /><br />
    <asp:TextBox ID="TextBox1" runat="server" BorderColor="Black" BorderWidth="2px" 
        Width="212px" Height="29px"></asp:TextBox>&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button1"
        runat="server" Text="Search" />
        <br /><br />
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="EId" 
            DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" 
            Width="580px">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="EId" HeaderText="EId" ReadOnly="True" 
                    SortExpression="EId" InsertVisible="False" />
                <asp:BoundField DataField="EventType" HeaderText="EventType" 
                    SortExpression="EventType" />
                <asp:BoundField DataField="Date" HeaderText="Date" 
                    SortExpression="Date" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:SSConnectionString %>" 
            
        SelectCommand="SELECT [EId], [EventType], [Date] FROM [EventTable] WHERE (([Date] = @Date) OR ([EventType] = @EventType))"
         UpdateCommand="UPDATE EventTable SET [EventType]=@EventType, [Date]=@Date where [EId]=@EId" 
         DeleteCommand="DELETE FROM EventTable WHERE EId  = @EId">

            <SelectParameters>
                <asp:ControlParameter ControlID="TextBox1" Name="Date" PropertyName="Text" 
                    Type="String" />
                <asp:ControlParameter ControlID="TextBox1" Name="EventType" PropertyName="Text" 
                    Type="String" />
            </SelectParameters>
         </asp:SqlDataSource>
         <br/>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SSConnectionString %>" 
        SelectCommand="SELECT [EId], [EventType], [Date] FROM [EventTable]"
         UpdateCommand="UPDATE EventTable SET [EventType]=@EventType, [Date]=@Date where [EId]=@EId" 
         DeleteCommand="DELETE FROM EventTable WHERE EId  = @EId">
        </asp:SqlDataSource>

    <asp:GridView ID="GridView2" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="EId" 
        DataSourceID="SqlDataSource2" CellPadding="4" ForeColor="#333333" 
        GridLines="None">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="EId" HeaderText="EId" InsertVisible="False" 
                ReadOnly="True" SortExpression="EId" />
            <asp:BoundField DataField="EventType" HeaderText="EventType" 
                SortExpression="EventType" />
            <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>


    
</asp:Content>
