<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Admin_Transport.aspx.cs" Inherits="WebApplication4.Admin_Transport" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style1
        {
            width: 53px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br /><br /><br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SSConnectionString %>" 
    SelectCommand="SELECT * FROM [TransTable]"
    InsertCommand="INSERT INTO TransTable VALUES (@name, @km_h, @image)"
    UpdateCommand="UPDATE TransTable SET name = @name, km_h= @km_h, image = @image WHERE Tid = @Tid"
    DeleteCommand="DELETE FROM TransTable WHERE Tid = @Tid">

    <InsertParameters>
        <asp:ControlParameter Name="name" ControlID="txtname" Type="String" />
        <asp:ControlParameter Name="km_h" ControlID="txtkm" Type="Int32" />
        <asp:ControlParameter Name="image" ControlID="txtimage" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="name" Type="String" />
        <asp:Parameter Name="km_h" Type="Int32" />
        <asp:Parameter Name="image" Type="String" />
        <asp:Parameter Name="Tid" Type="Int32" />
    </UpdateParameters>
    <DeleteParameters>
        <asp:Parameter Name="Tid" Type="Int32" />
    </DeleteParameters>
    
         </asp:SqlDataSource>

    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Tid" 
        DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" 
        Width="362px">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />

        <Columns>
            <asp:BoundField DataField="Tid" HeaderText="Tid" InsertVisible="False" 
                ReadOnly="True" SortExpression="Tid" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Km_h" HeaderText="Km_h" SortExpression="Km_h" />
            <asp:BoundField DataField="Image" HeaderText="Image" SortExpression="Image" />
            <asp:TemplateField>
            <ItemTemplate>
                <asp:Image ID="Image1" runat="server" ImageUrl='<%#"images1/trans/"+ Eval("Image") %>' />
            </ItemTemplate>
            </asp:TemplateField>

        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>

    <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
    <tr>
        <td style="width: 150px">
            Name<br />
            <asp:TextBox ID="txtname" runat="server" Width="140" />
        </td>
        <td style="width: 150px">
            Km_h:<br />
            <asp:TextBox ID="txtkm" runat="server" Width="140" />
        </td>
        <td style="width: 150px">
            Image:<br />
            <br />
            <asp:FileUpload ID="FileUpload1" runat="server" />
            <asp:Image ID="Image1" runat="server" ImageUrl="~/images1/trans/" 
                Width="203px" />
            <br />
            <br />
            <asp:TextBox ID="txtimage" runat="server" Width="155px" 
                style="margin-top: 0px" />
            &nbsp;
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
                Text="Upload Image" />
        </td>
        <td class="style1">
            <asp:Button ID="btnAdd" runat="server" Text="Add Item" OnClick="Insert" 
                Width="70px" />
        </td>
    </tr>
</table>
</asp:Content>
