<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Admin_Catter.aspx.cs" Inherits="WebApplication4.Admin_Catter" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br /><br /><br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SSConnectionString %>" 
        SelectCommand="SELECT * FROM [CatteringTable]"
        InsertCommand="INSERT INTO CatteringTable VALUES (@Description, @Price, @Items)"
        UpdateCommand="UPDATE CatteringTable SET Description = @Description, Price= @Price, Items = @Items WHERE Id = @Id"
        DeleteCommand="DELETE FROM CatteringTable WHERE Id = @Id" >
     <InsertParameters>
        <asp:ControlParameter Name="Description" ControlID="txtdes" Type="String" />
        <asp:ControlParameter Name="Price" ControlID="txtprice" Type="Int32" />
        <asp:ControlParameter Name="Items" ControlID="txtitems" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="Description" Type="String" />
        <asp:Parameter Name="Price" Type="Int32" />
        <asp:Parameter Name="Items" Type="String" />
        <asp:Parameter Name="Id" Type="Int32" />
    </UpdateParameters>
    <DeleteParameters>
        <asp:Parameter Name="Id" Type="Int32" />
    </DeleteParameters>  
   </asp:SqlDataSource>

    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="Id" 
        DataSourceID="SqlDataSource1" Width="348px" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        CellPadding="4" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="Description" HeaderText="Description" 
                SortExpression="Description" />
            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
            <asp:BoundField DataField="Items" HeaderText="Items" SortExpression="Items" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
    <tr>
        <td style="width: 150px">
           Description:&nbsp;&nbsp; <br />
            <asp:TextBox ID="txtdes" runat="server" Width="140" />
        </td>
        <td style="width: 150px">
            Price:<br />
            <asp:TextBox ID="txtprice" runat="server" Width="140" />
        </td>
        <td style="width: 150px">
            Items:<br />
            <asp:TextBox ID="txtitems" runat="server" Width="140px" />
        </td>
        <td style="width: 100px">
            <asp:Button ID="btnAdd" runat="server" Text="Add Item" OnClick="Insert" 
                Width="70px" />
        </td>
    </tr>
</table>
    
</asp:Content>
